### ISSUE TITLE
Chyba - Soubory online - VIP webshare

### ISSUE THREAD

**Issue by kolikkulda** [mx3L/archivczsk-doplnky#1]
Prosim o opravu v default.py

V mojem Xtrend ET8000 s openATV 5.3.0 mi nejde v doplnklu online soubory VIP ucet na webshare.
Tak jsem po prozkoumani kodu nasel rozdilne hodnoty u p = webshare.WebshareContentProvider(username='', password='',filter=webshare_filter)

po prepsani viz nize uz VIP jde, zepta se jestli chi pouzit VIP ucet a i prehravani jde.

if __settings__('webshare_enabled') == 'true':
	p = webshare.WebshareContentProvider(__settings__('**webshare_user**'),__settings__('**webshare_pass**'),filter=webshare_filter)
	extra = {
			'vip':'0',
			'keep-searches':__settings__('webshare_keep-searches')
	}
	extra.update(settings)

Nejsem programator, jen mi stvalo proc to nejde, tak jsem hledal rozdil mezi kodem z KODI a na archivCZSK

Neslo by propojit soubory online s doplnkem Stream Cinema CZ/SK? Viz http://www.xbmc-kodi.cz/showthread.php?tid=876

Dekuji

**Comment by bbaronSVK** [comment]
dnes som skusil pridat moj plugin Stream Cinema do repozitaru. Neviem, ci ten moj pull #2 prejde, lebo neviem ci tam treba spravit nejake upravy, takze zatial som to len skopcil. Niesom si ale isty, ci by sa nemal radsej pouzivat submodul z mojho repozitara...kludne spravit specialny branch pre enigmu.
