### ISSUE TITLE
Stream cinema nefunguje a zhodi OpenAtv 6.1  

### ISSUE THREAD

**Issue by nikd1** [mx3L/archivczsk-doplnky#10]
Od minuleho tyzdna nefunguje Stream cinema plugin 1.2.0. na Dreambox 7080hd s OpenAtv 6.1
Nefuncnost trva aj vo verzii 1.2.1. Doteraz fungovalo bez problemov. Webshare je zaplateny.
Pripajam crashlog. Chyba nastane pri spusteni prehravania.
[enigma2_crash_1513067143.log](https://github.com/mx3L/archivczsk-doplnky/files/1552828/enigma2_crash_1513067143.log)

**Comment by vatlach** [comment]
vyvolanie virtual klavesnice crash

14:44:44.091 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
14:44:44.111 [DEBUG] Video addon content provider 'VideoAddonContentProvider(VideoAddon(Stream Cinema-1.2.1))' start...
14:44:44.171 [DEBUG] [plugin.video.stream-cinema-importer]  cannot found modul util
14:44:44.178 [DEBUG] [plugin.video.stream-cinema-importer]  cannot found modul xbmcprovider
14:44:44.184 [DEBUG] [plugin.video.stream-cinema-importer]  cannot found modul xbmcutil
14:44:44.194 [DEBUG] Cannot retrieve setting 'quality' - VideoAddon(Stream Cinema-1.2.1)
14:44:44.197 [DEBUG] Cannot retrieve setting 'order-episodes' - VideoAddon(Stream Cinema-1.2.1)
14:44:45.691 [DEBUG] [plugin.video.stream-cinema-importer]  cannot found modul Screens.NumericalTextInputHelpDialog
14:44:45.702 [DEBUG] [script.module.stream.resolver-importer]  cannot found modul Screens.NumericalTextInputHelpDialog
14:44:45.706 [DEBUG] [custom_sys-importer]  cannot found modul Screens.NumericalTextInputHelpDialog
14:44:46.711 [ERROR] Init VirtualKeyBoardCFG failed.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/menu.py", line 222, in __init__
    VirtualKeyBoard.__init__(self, session, entryName.encode('utf-8'), configEntry.getValue().encode('utf-8'))
TypeError: __init__() takes at most 3 arguments (4 given)

14:45:26.140 [DEBUG] Screen width 1280 px
14:45:26.143 [DEBUG] loading skin /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/skins/default_hd.xml

**Comment by mtester270** [comment]
mozes mi povedat aku verziu archivu pouzivas ? predpokladam ze novu nie tak?

@valtach ty tu nemotaj temy ak chces zaloz novu ... to ze ti padne virtualna klavesnica je problem tvojho image skus si naistalovat subssupport co je pri novom RELEASE archivu (temu som ti zmazal) ak ti to nepomoze tak bohuzial

**Comment by mtester270** [comment]
Skus si vratit spat stream resolver tento
https://github.com/mx3L/archivczsk-doplnky/raw/master/xbmc-doplnky/repo/script.module.stream.resolver/script.module.stream.resolver-1.7.3.zip

Ale si tam nainstaluj novu verziu archivu ak je to mozne

**Comment by nikd1** [comment]
Dal som novu verziu archivu czsk a vsetko je OK.
Dik
