### ISSUE TITLE
Addon Markiza

### ISSUE THREAD

**Issue by vatlach** [mx3L/archivczsk-doplnky#12]
Addon Markiza - pri prehravani Televizne Noviny alebo Prve Televizne noviny prehra len uputavku v dlzke cca 4x sekund a nasledne vyhodi do menu addona.Je to mozne fixnut? Vdaka
log:
17:03:59.026 [DEBUG] PicLoad getData...
17:03:59.026 [DEBUG] PicLoad getData finished
17:03:59.027 [DEBUG] SetPixmap...
17:03:59.027 [DEBUG] SetPixmap finished
17:03:59.391 [DEBUG] Opening item '<PVideoNotResolved - Televízne noviny - 25.január 2018>'...
17:03:59.404 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul util
17:03:59.405 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcprovider
17:03:59.406 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcutil
17:03:59.407 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul resolver
17:03:59.408 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul provider
17:03:59.409 [DEBUG] Cannot retrieve setting 'quality' - VideoAddon(markiza.sk-1.1.5)
17:04:01.386 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul util
17:04:01.387 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcprovider
17:04:01.388 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcutil
17:04:01.389 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul resolver
17:04:01.390 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul provider
17:04:01.391 [DEBUG] Cannot retrieve setting 'quality' - VideoAddon(markiza.sk-1.1.5)
17:04:01.394 [DEBUG] Stats (play) call success.
17:04:49.183 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul util
17:04:49.185 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcprovider
17:04:49.187 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul xbmcutil
17:04:49.189 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul resolver
17:04:49.191 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul provider
17:04:49.193 [DEBUG] Cannot retrieve setting 'quality' - VideoAddon(markiza.sk-1.1.5)
17:04:49.196 [DEBUG] Stats (end) call success.
17:04:52.214 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul sys
17:04:52.215 [DEBUG] [script.module.stream.resolver-importer]  cannot found modul sys
17:04:52.216 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul builtins
17:04:52.217 [DEBUG] [script.module.stream.resolver-importer]  cannot found modul builtins
17:04:52.218 [DEBUG] [custom_sys-importer]  cannot found modul builtins
17:04:52.702 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul sys
17:04:52.703 [DEBUG] [script.module.stream.resolver-importer]  cannot found modul sys
17:04:52.704 [DEBUG] [plugin.video.markiza.sk-importer]  cannot found modul builtins
17:04:52.705 [DEBUG] [script.module.stream.resolver-importer]  cannot found modul builtins
17:04:52.706 [DEBUG] [custom_sys-importer]  cannot found modul builtins

**Comment by mtester270** [comment]
done + nastavenie aky sposob nacitavanie chcete pouzit
