### ISSUE TITLE
po instalaci nefunkční tlačítko OK na ovladači a ENTER na klávesnici 

### ISSUE THREAD

**Issue by glumik24** [mx3L/archivczsk-doplnky#15]
chtěl jsem se zeptat jestli nemá nebo neměl podobný problém. Po instalaci pluginu archivczsk po spuštění czsk archivu nelze potvrzovat výběr na ovladači (OK tlačítko) i klávesnici(enter). Přístroj Amiko Alien 5 system openatv6

**Comment by mtester270** [comment]
Ak ti to nejde tak zmen VZHLAD v tom openatv6, ale ked uz moc chces zapni si debug pre system a nasimuluj to a potom sa pozri v krabici co ti to tam pise ale toto dost pochybujem ze tusis o com tocim 💃 

Posledna moznost zmen Image napr VTi, Blackhole, ...

**Comment by hansolo272** [comment]
Presne tak príteli 
bez logu není pomoci 
A5 krom openatv nic zdá se není venku ,nová krabice 
dualboot android flash /enigma sd card  :-)

**Comment by mtester270** [comment]
Predpokladam ze si si to vyriesil u seba kedze.chyba nie je v archive takze zatvaram

**Comment by glumik24** [comment]
bohuzel jsem to zatím nevyřešil

**Comment by glumik24** [comment]
jak mám zapnout debug pro system jsem v tomhle začátečník

**Comment by mtester270** [comment]
Hladaj radu po forach napr. AB, nejedna sa o chybu doplnku ale len o problem tvojho boxu a systemu co tam mas. Takze studuj nikto mudry z neba nespadol
