### ISSUE TITLE
Huste TV plugin

### ISSUE THREAD

**Issue by tranzistor20** [mx3L/archivczsk-doplnky#16]
V KODI plugine StreamCinema verzie 1.3.10 bola opravena (aj) sluzba Huste TV live .. Uzivatelia KODI uz ju mozu veselo pouzivat tak som sa chcel opytat ci by ju bolo mozne zakomponovat do novej verzie ArchviCZSK pluginu...

Viac info tu: http://www.xbmc-kodi.cz/prispevek-huste-live?highlight=huste

**Comment by mtester270** [comment]
Jo bude

**Comment by hansolo272** [comment]
no s pánem bohem , nemužu se dočkat  :-)

**Comment by hansolo272** [comment]
dočkal si se aktivní v 1.1.2 / 1.3.6
tranzistore ,tak si to pusť a pro jistotu si dej tak 5-6 štamprlí :-)

**Comment by tranzistor20** [comment]
Nechcem nikoho sklamat ale nech zvolim akykllvek stream a akukolvek kvalitu hned ma to vrati spat na vyber streamov z huste

...samozrejme skusam po aktualizacii

**Comment by hansolo272** [comment]
nikoho nesklameš tranzistore
u mne vše jede až na to že to seká trhá kmitá 
test jak v mipselu tak u kolegy v armu ,vlc v pc taky nic moc hold stream nevalné kvality:-)
a v tmp ti tvuj stream-cinema.log napoví co ? postuduj si , popremýšlej

**Comment by tranzistor20** [comment]
No ..na octagone sf 4008 sa mi to sprava tak ako som popisoval ..na formuler f4 turbo to ide tak ako popisujes ty... trha,seka - nepozeratelne ...ale to trhanie pripisujem linke...   cez telekom VDSL to trha aj cez kompa... ked sa pripojim cez mobil a zrkadlim na telke , ide to z netu plynulo ... No yo... kuknem logy a ak na nieco pridem, dam sem vediet.

**Comment by tranzistor20** [comment]
No ..na octagone sf 4008 sa mi to sprava tak ako som popisoval ..na formuler f4 turbo to ide tak ako popisujes ty... trha,seka - nepozeratelne ...ale to trhanie pripisujem linke...   cez telekom VDSL to trha aj cez kompa... ked sa pripojim cez mobil a zrkadlim na telke , ide to z netu plynulo ... No yo... kuknem logy a ak na nieco pridem, dam sem vediet.

**Comment by hansolo272** [comment]
já jedu na optice a je to nanic i boxech VU+ tak v pc
nejaký android mne nezajíma jak ti to jede v mobilu atd
tohle je pro mne naprosta zbytečnost , huste streamy atd 
pokud se ti bude venovat tvurce doplnku respekt 
pro mne je to stráta času  -- end --

**Comment by mtester270** [comment]
S tym ze ti to seka ti nebudem vediet pomoct, co sa tyka neprehravania tak bez logu nic, ale problem bude v image co mas v boxe na 99% ;-)

**Comment by tranzistor20** [comment]
formuler je u svagra na vdsl.. ja mam doma 100Mbps optiku ...ale ja mam zas ten problem ze ten stream ani neospustim.. Cez kodi aj cez kompa to u mna ide pozeratelne ..resp staci mi to tak..

Image v mojom octagone by som velmi menit nechcel .. mam to dost kustomizovane, kedze box pouzivam iba na IPTV, taham do toho skriptatmi EPG, mam tam zapracovany kamerovy system z prace  atd atd .. a uprimne sa mi to nechce zasa cele odznova riesit. Podstatne je ze na inych E2  boxoch to uz cez streamcinemu chodi.. Do piatku na to pozriem a uvidim ci s tym viem nieco vyriesit alebo nie... Zatial ale velmi pekne dakujem za snahu.
