### ISSUE TITLE
Plugin Markiza

### ISSUE THREAD

**Issue by mukates** [mx3L/archivczsk-doplnky#29]
Ahoj, v plugine markiza sa v archive pre serial Horna dolna zobrazuje vzdy iba posledna cast + cast s nazvom Meda beda. Nejaka rada, alebo fix? Vti 14.0.3, Archiv CZ/SK premium.

**Comment by hansolo272** [comment]
TV doplnky 
krátka životnost tak mesíc dva a down
porád menit py soubory pro fix nemá smysl 
Horná Dolna
 použi doplnek s.cinema /archiv premium je tam vše v serial

pro inkognito
joj  bez komentáre

**Comment by mtester270** [comment]
netrafil si spravny github trosku :-) (teda aspon podla verzie archivu co si ani hansolo nevsimol :-D)

**Comment by hansolo272** [comment]
nevšiml omluva 

ale ted mám totál chaos 

protože tv joj vidím nový
fix v starém archivu ve verzi 1.3.10 aktuálne test ok 
to je chaoss to je chaoss ---  :-D

**Comment by mukates** [comment]
Ahoj, no stalo sa toto. Po zapnuti archivu CZSK mi to vyhodilo aktualizaciu, potom, ci chcem vyskusat Archiv Premium, tak preco nie. Chvilku na to mi to vyhodilo dalsiu aktualizaciu ma verziu 1.0.1 s informaciou o platbe. OK, ved predsa aktualizacie zaberaju cas aj vedomosti {mam 3 boxy, tak som poslal platbu za kazdy}. Pozeram ale, ze vsetky doplky v tomto premium archive maju verziu 1.0.0. Tak som z toho uplne zmeteny. Tento "Issue" zatvaram a presuvam na github CZSK Premium :-)
