### ISSUE TITLE
Stream Cinema

### ISSUE THREAD

**Issue by Ornela777** [mx3L/archivczsk-doplnky#33]
Dobrý deň,
prosím vás prečo mi nejde spustiť film cez Stream Cinema doplnok na Archiv czsk keď cez kodi na PC filmy v pohode prehrám. Ďakujem Jano zo Slovenska

**Comment by misanov** [comment]
Pěkný den, doplněk Stream Cinema již není autorem podporován, pracuje se na novém Stream Cinema 2.0, který v archivu je taktéž, ale je to ještě hodně alpha, tzn. plno věcí tam chybí, dělá se od začátku.
