### ISSUE TITLE
Problem so spustením 

### ISSUE THREAD

**Issue by tomasxiii** [mx3L/archivczsk-doplnky#38]
![IMG_20201126_132723](https://user-images.githubusercontent.com/59908387/100370039-f77bfd80-3005-11eb-9e36-40f74f25749e.jpg)

**Comment by misanov** [comment]
Toto není problém pluginu, ale dostupnosti serveru.

**Comment by tomasxiii** [comment]
Avšak cez Kodi s prihlásením problém nie je. 
Sent from Yahoo Mail on Android 
 
  On št, nov 26, 2020 at 16:53, Michal Novotný<notifications@github.com> wrote:   


Closed #38.

**Comment by misanov** [comment]
Pak musí být nějaký problém v komunikaci mezi boxem a serverem. Co je to za box? Je nějaká chyba v logu? Nejlépe se zapnutým logováním ladění (debug). Ideálně tento zaslat po nastavení debug a vyhození této hlášky.

**Comment by tomasxiii** [comment]
Je to Octagon sf8008 s enigmou 2. Nie som teraz doma avšak aj tak ak by ste mi prosím napísali ako ten debug urobiť a poslať tak tak rád urobím. 

Sent from Yahoo Mail on Android 
 
  On št, nov 26, 2020 at 17:08, Michal Novotný<notifications@github.com> wrote:   


Pak musí být nějaký problém v komunikaci mezi boxem a serverem. Co je to za box? Je nějaká chyba v logu? Nejlépe se zapnutým logováním ladění (debug). Ideálně tento zaslat po nastavení debug a vyhození této hlášky.

**Comment by misanov** [comment]
V Nastavení v záložce Různé je Ladění - info nebo debug, přepnout na debug. Pak log by měl být v /tmp/archivczsk.log

**Comment by tomasxiii** [comment]
No snáď sa z toho budete vyznať a snáď tam nájdete chybu. Ďakujem krásne za pomoc. 

    On Thursday, 26 November 2020, 21:55:37 CET, Michal Novotný <notifications@github.com> wrote:  
 
 


V Nastavení v záložce Různé je Ladění - info nebo debug, přepnout na debug. Pak log by měl být v /tmp/archivczsk.log

**Comment by misanov** [comment]
Hlavně ten log přiložit na githubu ;-)

**Comment by tomasxiii** [comment]
[archivCZSK.log](https://github.com/mx3L/archivczsk-doplnky/files/5605101/archivCZSK.log)

**Comment by misanov** [comment]
Máte Stream Cinema Community-2.1.9 a nejnovější je Stream Cinema Community-2.1.14, aktualizace funguje? Máte zapnuté? Už od 2.1.11 byly změny na serveru, tož to ani nemůže jít.

**Comment by tomasxiii** [comment]
Áno. Mám ju zapnutu avšak zjavne mi to automaticky nestiahne

Sent from Yahoo Mail on Android 
 
  On št, nov 26, 2020 at 23:01, Michal Novotný<notifications@github.com> wrote:   


Máte Stream Cinema Community-2.1.9 a nejnovější je Stream Cinema Community-2.1.14, aktualizace funguje? Máte zapnuté?

**Comment by tomasxiii** [comment]
Aktualizované. Vymazal som, nahral znova a ponúklo mi hneď aj aktualizáciu. Ďakujem. Škoda len, že teraz zas vyhadzuje problém s prihlásením. Ale to už zajtra resp. dnes. Dobrú noc a vďaka za pomoc. 

Sent from Yahoo Mail on Android 
 
  On št, nov 26, 2020 at 23:37, Tomas Hloska<tomashloska@ymail.com> wrote:   Áno. Mám ju zapnutu avšak zjavne mi to automaticky nestiahne

Sent from Yahoo Mail on Android 
 
  On št, nov 26, 2020 at 23:01, Michal Novotný<notifications@github.com> wrote:   


Máte Stream Cinema Community-2.1.9 a nejnovější je Stream Cinema Community-2.1.14, aktualizace funguje? Máte zapnuté?
