### ISSUE TITLE
SC2 2.1.15 NONE místo některých souborů

### ISSUE THREAD

**Issue by DavidAntonin** [mx3L/archivczsk-doplnky#39]
Pokud dám vyhledat video, např. slunečná,  tak mi to nalezne složku slunečná, v ní jsou 2 složky série 1 a série 2.  Pokud však otevřu tyto složky, je v obou složka "NONE". Tento problém se netýká pouze uvedeného seriálu. 
Díky

**Comment by misanov** [comment]
Dva dny stará aktualizace SCC 2.1.16 toto řeší.

**Comment by DavidAntonin** [comment]
I po aktualizaci na 2.1.16 u některých seriálů stále NONE, napři Susedia - 2020

**Comment by misanov** [comment]
To už musíte řešit na streamcinema.cz, proč tam nejsou epizody, tento jejich doplněk zobrazuje jen obsah od nich.
