### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by DavidAntonin** [mx3L/archivczsk-doplnky#41]
Ahoj, děkuji za poslední opravu YouTube. Nyní se videa načítají i přehrávají. Nemůžu však u videí vybrat nejvyšší kvalitu, např. 4K s HDR. Přijímač VU+ Uno 4K, poslední verze VTi 15.

**Comment by misanov** [comment]
Nemohu to nějak vyzkoušet, nemám 4K, už to ve v1.3 funguje?

**Comment by DavidAntonin** [comment]
Teď mi to nefunguje vůbec - chyba HTTP:404

**Comment by digitas** [comment]
@DavidAntonin 
Mne youtube plugin nefunguje už cca 2 mesiace a predtým fungoval OK cca mesiac aj HD, ale 4K nemám
