### ISSUE TITLE
Stream Cinema Community

### ISSUE THREAD

**Issue by DavidAntonin** [mx3L/archivczsk-doplnky#42]
Mám problém s přístupem k seriálům, pokud je v sérii více jak 100 dílů. Aktuálně např. Slunečná.
Díly 1-100 jsou v pořádku, další se nezobrazí. V přehrávači YMovie.streamcinema.cz  se po 100. díle zobrazí složka s dalšími díky 101...
Díky

**Comment by misanov** [comment]
Opraveno.
