### ISSUE TITLE
Videacesky.cz doplněk

### ISSUE THREAD

**Issue by ondrej88** [mx3L/archivczsk-doplnky#43]
Ahoj,
mám VU+ZERO4K s nainstalovanou nejnovjší verzí VTi a CZ/SK Archivem a mám problém s doplňkem videacesky.cz,
Spustím doplněk, vidím videa k přehrání(náhled s popiskem), ale po výběru videa vyskočí chyba "chyba archivu, autor jej musí opravit" a jsem zase zpátky v přehledu videí. Nějaké nápady?

Předem díky

**Comment by misanov** [comment]
Vyzkoušeno nyní Nejnovější - Historie plastů a i další a jede v pořádku. Pokud tedy problém přetrvává, prosím zaslat archivCZSK.log z adresáře /tmp po dané chybě.

**Comment by ondrej88** [comment]
Děkuji za zpětnou vazbu. Jen jsem nějak nezjistil, kde najdu ten log s chybou. Stáhl jsem si modul na procházení adresáře interního uložiště přijímače, ale adresář /tmp s logy jsem nenašel:/

**Comment by misanov** [comment]
Zkuste přístup přes FTP

**Comment by ondrej88** [comment]
Díky, povedlo se. Log v příloze. 
[archivCZSK.log](https://github.com/mx3L/archivczsk-doplnky/files/6875927/archivCZSK.log)

**Comment by ondrej88** [comment]
Tak doplněk začal sám od sebe fungovat. Možná proběhl nějaký update, nevím. 
Díky O.
