### ISSUE TITLE
 plugin.video.ta3.com

### ISSUE THREAD

**Issue by digitas** [mx3L/archivczsk-doplnky#44]
Zdravím, kvôli zmene na stránke je už cca mesiac takmer nefunkčný plugin.
Skúšal som upraviť ta3.py, ale nedarí sa mi to rozchodiť. Vedel by prosím niekto opraviť?
Live stream je OK.
Dík.

**Comment by kajost** [comment]
Uz to tu mas riesene
[Tu](https://github.com/mx3L/archivczsk/issues/130)

**Comment by misanov** [comment]
Opraveno

**Comment by digitas** [comment]
@misanov Vďaka za opravu.
