### ISSUE TITLE
plugin.video.ta3.com tlačovky

### ISSUE THREAD

**Issue by digitas** [mx3L/archivczsk-doplnky#45]
@misanov Vďaka za opravu.
Prosím ešte, ak by sa dalo doplniť sekciu Tlačové besedy. Tie som práve najviac sledoval.
Predtým som mal v plugine doplnené TB - riadok result.append(self.dir_item('TB', 'https://www.ta3.com/tlacove-besedy#mycat')). 
Teraz sú ale videá na stránke vnorené pod jednotlivými článkami https://www.ta3.com/clanok/číslo...

Tiež by bolo fajn radenie podľa dátumu.
Dík.

**Comment by digitas** [comment]
Alebo super by bolo na tlačovky pridanie nového pluginu - napr.
**TV NRSR** - https://tv.nrsr.sk/archiv/tlacovakonferenciavsetky  alebo
**TASR TV**  - https://www.tasrtv.sk/live/ záznamy tlačoviek

**Comment by misanov** [comment]
Doplněk byl přepsán a myslím, že nyní budete spokojeni.

**Comment by digitas** [comment]
Ďakujem za opravu.
