### ISSUE TITLE
plugin.video.ta3.com iba jeden Live stream

### ISSUE THREAD

**Issue by digitas** [mx3L/archivczsk-doplnky#47]
Ako vylepšenie dávam podnet na úpravu ta3.py na odstránenie výberu kvality rozlíšenia z troch pri LIVE streame, nakoľko je na stránke len jeden v 360p. Zrýchlilo by to spúšťanie-Live na jedno stlačenie tlačítka.

**Comment by misanov** [comment]
Toto lze odstranit v Nastavení výběrem Kvality, např. Nejlepší, a již se nebude ptát.
