### ISSUE TITLE
Nefunguje automaticke nacitanie tituliek Stream Cinema Community

### ISSUE THREAD

**Issue by celgi** [mx3L/archivczsk-doplnky#54]
Dobry den,

chcem sa spytat ako presne ma fungovat Stream Cinema Community a SubSupport. Na starej Stream Cinema mi to fungovalo tak, ze ked som pustil film z titulkami tak mi automaticky nacitalo titulky. V novej Stream Cinema Community mi titulky automaticky nenacita, musim spustit SubSupport, manualne ich vyhladat, stiahnut a nasledne dam vybrat a uz mi funguju. Ma to fungovat automaticky ako kedysi ? Alebo mam niekde chybu ? Dakujem za kazdu radu. A ospravedlnujem sa ak som zle zalozil prispevok. Verziu SubSupport mam 3.0.0.

**Comment by celgi** [comment]
> Dobry den,
> 
> chcem sa spytat ako presne ma fungovat Stream Cinema Community a SubSupport. Na starej Stream Cinema mi to fungovalo tak, ze ked som pustil film z titulkami tak mi automaticky nacitalo titulky. V novej Stream Cinema Community mi titulky automaticky nenacita, musim spustit SubSupport, manualne ich vyhladat, stiahnut a nasledne dam vybrat a uz mi funguju. Ma to fungovat automaticky ako kedysi ? Alebo mam niekde chybu ? Dakujem za kazdu radu. A ospravedlnujem sa ak som zle zalozil prispevok. Verziu SubSupport mam 3.0.0.

Už som na to prišiel ;)

**Comment by tranzistor20** [comment]
Tak prezrad...aj mna to zaujima...ja to pustam tak ze v scc dam film
stiahnut, a potom si ho pustam cez prehliadac suborov...tam sa titulky
nacitaju automaticky

Dňa so 22. 1. 2022, 12:25 celgi ***@***.***> napísal(a):

**Comment by celgi** [comment]
> Tak prezrad...aj mna to zaujima...ja to pustam tak ze v scc dam film stiahnut, a potom si ho pustam cez prehliadac suborov...tam sa titulky nacitaju automaticky Dňa so 22. 1. 2022, 12:25 celgi ***@***.***> napísal(a):
> […](#)

pustis si film priamo zo stream cinema (nedavas ho stahovat) následne stlacis na ovladaci tlacitko tituliek a potom stlacit cervene tlačítko vybrat vnorené titulky
