### ISSUE TITLE
Sosac a StreamCinema - VTI

### ISSUE THREAD

**Issue by vatlach** [mx3L/archivczsk-doplnky#6]
Po upgrade Sosac na verziu 1.2.6 a po zadani mena a hesla aj bez neprehra nic.
StreamCinema po zadani mena a hesla seka pri kazdej kvalite.(buffer???)  (Kodi OK).

**Comment by mx3L** [comment]
Boli my poskytnute udaje, testol som na About a boy - 1x pilot, prehravat, pretacat islo aj stahovanie fungovalo, aspon co som testoval na enigma2pc s gstplayer,

**Comment by radasol** [comment]
Změna asi souvisí s resolverem, protože mě osobně neukáže přímo streamy, adresářová struktura jede

**Comment by radasol** [comment]
Po větším zkoumání jsem zjistil, že filmy s nápisem SD jedou, s HD vykopnou stejně jako seriály, testováno například na 2 Socky

**Comment by mx3L** [comment]
Tak vcera tesne pred releasom som urobil chybu z odsadenim :), snad to uz pojde..

**Comment by vatlach** [comment]
Ano uz to ide ok sosac 1.2.7. 
Bohuzial ovplyvnilo to StreamCinema,kde nejde ziaden stream ak bol predtym stream zo sosaca.Musi sa restartnut Enigma,aby to bolo funkcne.
Je mozne sa pozriet este na vlozenie user,password cez virtualnu klavesnicu?
ostava tam userXcursorX a passwordXcursorX.
Pri vlozeni klasickym sposobom je to ok.
Chyba ArchivCZSK ci image?
Vdaka za support.

**Comment by radasol** [comment]
Ano, večer se zena divala
______________________________________________________________
> Od: mx3L <notifications@github.com>
> Komu: mx3L/archivczsk-doplnky <archivczsk-doplnky@noreply.github.com>
> Datum: 07.08.2017 19:14
> Předmět: Re: [mx3L/archivczsk-doplnky] Sosac a StreamCinema - VTI (#6)
>
Tak vcera tesne pred releasom som urobil chybu z odsadenim :), snad to uz pojde..

**Comment by rak217** [comment]
Chtěl bych poprosit o zapracování na chybě v nastavení (modré tlačítko)... Na VU+ (VTI) po zmáčknutí modrého tlačítka totální zámrz a lze jen hard reboot. Bohužel nelze se pak dostat k zadání loginu streamuj.tv :-(
Díky

PS: po několika testech jsem zjistil, že problém je ve skinu... ve VTI 11  je výchozí skin VU_HD_1080p, kde se vše sekne, pokud se vymění skin na AtilleHD, pak je vše OK

**Comment by vatlach** [comment]
Sosac blokuje StreamCinema.Tu je log,ked je prvy spusteny sosac a potom streamcinema

19:31:18.074 [e2-python] playing service..
19:31:18.098   [e2-core] eServiceMP3::construct!
19:31:18.120 [e2-python] getResolvedKey config.mediaplayer.useAlternateUserAgent failed !! (Typo??)
19:31:18.144 [e2-python] getResolvedKey config.mediaplayer.extraHeaders failed !! (Typo??)
19:31:18.164   [e2-core] eServiceMP3::playbin uri=plugin://plugin.video.online-files/?play=.......
19:31:18.185   [e2-core] eServiceMP3::starting pipeline
19:31:18.223 [e2-python] [SubsSupport] Service Started
19:31:18.253 [e2-python] [SubsLoader][info] changing encoding group to: ['utf-8', 'utf-16', 'windows-1250', 'iso-8859-2', 'maclatin2', 'IBM852']
19:31:18.274 [e2-python] [SubsEngine] setSubsDelay - setting delay to 0ms
19:31:18.298 [e2-python] [SubsLoader][info] changing encoding group to: ['utf-8', 'utf-16', 'windows-1250', 'iso-8859-2', 'maclatin2', 'IBM852']
19:31:18.314 [e2-python] [SubsEngine] setSubsDelay - setting delay to 0ms
19:31:18.344   [e2-core] eServiceMP3::state transition NULL -> READY
19:31:18.364   [e2-core] Gstreamer error: No URI handler implemented for "plugin". (domain:2167, code:12) from uridecodebin1
19:31:18.763   [e2-core] gst_element_query_position failed in getPlayPosition
19:31:18.785   [e2-core] gst_element_query_position failed in getPlayPosition
19:31:18.809   [e2-core] gst_element_query_position failed in getPlayPosition
19:31:18.824   [e2-core] gst_element_query_position failed in getPlayPosition

**Comment by mx3L** [comment]
no vidim ze posiela prehravacu plugin url co je nezmysel. Nevidim dovod preco by sa to malo diat, potrebujem to reprodukovat lokalne. 

Takze potrebujem presny postup, tj ktore video mam dat prehravat ( aj vyber kvality ) a funguje v stream cinema a nasledne nefunguje ak spustime prvy sosac.

**Comment by vatlach** [comment]
skus sosac(masaryk2016 - 720p) a nasledne streamcinema (piaty element CZ 1080p).

**Comment by mx3L** [comment]
Ktory piaty element funguje v stream cinema predtym ako spustim sosac? Je tam viac s kvalitou 1080p.

**Comment by vatlach** [comment]
2,05GB druhy zvrchu

**Comment by mx3L** [comment]
Spustil som [1080p][ CZ] Pátý element 2.05 GB  bez toho aby som spustal sosac a nefunguje, takisto posle pluginurl ako v logu. Cize nemoze to fungovat.

**Comment by vatlach** [comment]
mne to ide,len v logu nepise nic,pretoze nie je chyba.Skus restartnut E2 a znovu.S prihlasenim.Bez neho nejde.

**Comment by mx3L** [comment]
Ja to pustam na pc cez enigma2pc, prihlasenie ako, ze treba mat prihlasovacie udaje aby mi to fungovalo?

**Comment by vatlach** [comment]
ano username a pass aj pre streamcinema

**Comment by mx3L** [comment]
aha tak tym to bude, ok akurat mi poslali na test :) tak vyskusam..

**Comment by radasol** [comment]
Když už jsme u streamcinema, je možné použít nové seznamy ze stream-cinema.online/kodi ?

**Comment by mx3L** [comment]
opravene, @radasol neviem co myslis..

**Comment by vatlach** [comment]
odskusane.
