### ISSUE TITLE
Sosac  - chyba přetáčení

### ISSUE THREAD

**Issue by radasol** [mx3L/archivczsk-doplnky#7]
Narazil jsem na chybu, nejspíše jde o chybu předání jména a hesla. Prostě některé položky jdou bez problému přehrát a některé zamrznou, jako by nebyl přihlášený. Například. DR.House jede v pořádku, včetně přetáčení, 2Socky -1x1 Pilot nejede.

**Comment by vatlach** [comment]
Pretacanie nejde vsade.Ale prehravanie ide.

**Comment by radasol** [comment]
Přiznám se, neskoušel jsem, zda to jede i po minutě. Bral jsem to tak, že automaticky nejede. Je to tak, opravdu přehrává dále, ale neposouvá. Asi problém s novým kodem z KODI

**Comment by speedo919** [comment]
Caute. Venuje sa niekto sosacu? To pretacanie by fakt bodlo. Aj ked u mna prehrava iba filmy v html5. Tie co su po starom idu iba minutu... Pretacanie vobec.

**Comment by 1terit1** [comment]
Zdravim. Taky mam stejny problem. U nekterych filmu mohu pretacet ( vu+ zero , E2 ) a u nekterych ne. Nevite v cem muze byt problem ?

**Comment by mtester270** [comment]
Fixed v novej verzii bude ok

**Comment by 1terit1** [comment]
Zdravím. 

Máte představu kdy asi bude nová verze ? Ptám se proto , jestli mam teda zůstat u vás , nebo jít k stream cinema . Tam vše funguje bez problémů . Děkuji za odpověď

**Comment by mtester270** [comment]
Neviem kedy bude nova verzia lebo jednak ma za to nikto neplati a az na jednu vynimku nepodpori!!!

Bavime sa o novej verzii archivu nie pluginu Sosac. Len tak pre tvoje info ja nemam s pluginmi nic spolocne teda niesom ich prevadzkovatel ani nic podobne proste len vylepsujem archiv vo volnych chvilach.

Kazdopadne prechod na StreamCinema mozem len doporucit za mna je lepsi pokial nemas slabucky internet

**Comment by 1terit1** [comment]
Joj. Tak to samozřejmě já nevím. Myslel jsem , že Jste placen z příjmů toho sosáče  potažmo , že si píšu z někým ze sosáče. Ti by měli mít zájem na tom , aby služba kterou poskytují byla kvalitní. Jak bych vás musel podpořit , aby jste mi to rozchodil ?

**Comment by 1terit1** [comment]
Promiň. V první chvíli jsem nedočetl celý email.  Teď to už trochu chápu . Takže ještě pár dotazů. Proč to začalo blbnout až při zpoplatnění ? Doté doby jsem byl maximálně spokojený . Proč mi některé filmy i seriály přetáčet jdou a některé ne ? Co se týká té cinemy.  Mám VU+ zero.  Na počítači v KODI vše fungovalo dobře . Ale na satelitu mi to přišlo hodně nepřehledné . Navíc se mi to sekalo . Mám asi 10Mbitovou linku ( bydlím na vesnici ) . A někdy v podvečer mívám problém i se sosáčem. TA linka je tedy myslíš nedostačující ? Dik za odpověď

**Comment by mtester270** [comment]
1) preco zacal blbnut sosac je snad jasne 💃 (sosac zmenil nieco v datach). Ak mi prepacis tak preco prestal ist sosac v plugine ti neprezradim (ale je to opravne, http://www.ab-forum.info/viewtopic.php?f=131&t=45682&start=920). Ak chces tak za podporu sa vieme dohodnut a nemam problem ti to individualne rozchodit tym padom nemusis cakat na update archivu.

2) ak mas VU zero tak problem v prehravani videa 1080p nemoze mat problem aj pri 16GB filme. Ja mam tiez VU ale solo2 a tusim ze to ma skoro rovnake parametre a vsetko slape. Pokial ti filmy na PC prehravalo vporiadku tak to tipujem ze to ZERO mas pripojene cez WIFI co moc nedoporucujem urcite prehodit na kabel. 10Mbit linka ak je stabilna tak teoreticky na StreamCinema filmik o velkosti 2 az 3GB by si nemal mat problem prehrat aj ked tam vstupuje vela faktorov (provider, stabilita pripojenia, atd...)

**Comment by 1terit1** [comment]
Ahoj

Koukám na filmy 720p. A vu+ zero mám na kabelu. Fungovalo mi to dobře v 
kodi na pc ale na vu+ kodi nemám. Tam mám jen archivy czsk. Kolik chceš 
přispět? Budu rád když to bude fungovat, pokud to teda nebude nějaká 
katastrofální částka

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 14. listopadu 2017 14:53:00 mtester270 <notifications@github.com> napsal:

**Comment by mtester270** [comment]
Ciastka je dobrovolna. Sluzi len na motivaciu a uvedomenie ludi ze nie vsetko je zadarmo co sa tvari zdarma.
Zvysok poprosim kontakt emailom, ak sa posnazis tak najdes kde napisat

**Comment by mtester270** [comment]
Ohladom stream cinema tak tam su tie veci kvalitnejsie teda maju viac GB tym padom vacsia narocnost na internet a je potrebne mat zaplateny ucet na webshare. Zvysok studuj forum bud ab-forum alebo xbmc kodi

**Comment by 1terit1** [comment]
Ted ti teda uplne nerozumim . Co se tyka kvality , tak ta pro me neni zase tak dulezita . Takze 720 p na sosaci mi vice než vyhovuje . Co se tyka placení , tak jsem si samozřejme zaplatil ůčet na webshare , ale jak jsem psal nebyl jsem z toho nikterak nadšeny . Stejne tak mam ted zaplaceny sosač , jinak bych asi nemohl dneska koukat . Co se tyka častky , kolik mam uhradit , tak to musis rict ty . Pokud to bude rozumne , tak nemam problem ti to poslat a samoze nikde otom nemluvit . Ty pomuzes mne a ja s tim teda opravdu nemam zaden problem . Urcite to je pro mne jednoduchsi , nez na nejaky film koukat x krat , jelikoz se mi to pri pause kousne a ja pak musim koukat znova :D
