### ISSUE TITLE
Aktualizace StreamCinema 1.1.2

### ISSUE THREAD

**Issue by radasol** [mx3L/archivczsk-doplnky#8]
Chyba v přihlašování ? Náhodně ukazuje, že se nelze přihlásit. Po vrácení na předchozí verzi vše ok.

Testováno třeba na HoT 7 serie

**Comment by Zmurko** [comment]
Oprava bude v najblizsej aktualizacii...Autor uz o tom vie ;)

**Comment by mtester270** [comment]
opravene hosi uz len cakam na release novej verzie par veci som tam aj pridal vid. change.log

zatvaram

**Comment by radasol** [comment]
Skvělá práce, jede to jak má, aspoň co jsem zjistil
