### ISSUE TITLE
Sosáč nepřehrává další verze, když je jich víc

### ISSUE THREAD

**Issue by bug78** [mx3L/archivczsk-doplnky#9]
Ahoj, na sosáči, když je u filmu více verzí např. Transformers: Poslední rytíř nebo Strážci Galaxie 2 verze 720p česky je tam dvakrát tak se vždy přehraje jen ta první verze i když si dám tu druhou.
U těch Strážců je to vidět dobře protože ta první verze je nějaký jiný film.
Když si to pustím přes kodi na svém pc tak normálně přehraju i tu druhou verzi kde je správný film v cz.

**Comment by mtester270** [comment]
Pozrel som ockom plugin ziadny rozdiel nevidim takze problem asi v datach co posiela sosac takze skus napisat sem http://movies.sosac.tv/cs/

Fakt odomna nechci aby som to tu hladal ze preco tebe nejdu dva streamy. Skus najst chybu sam a potom ti to tu viem dat. Pripadne skus pouvazovat nad zmenou na StreamCinema tam som takyto problem nezaznamenal
